export const deployments = [
  {
    id: 1,
    name: "inventory-api",
    image: "registry.local/inventory-api:v2.3.1",
    namespace: "production",
    status: "Running",
    replicas: 4,
    readyReplicas: 4,
    cpu: "125m",
    memory: "256Mi",
    created: "2 hours ago",
    sortDate: 1,
    port: 3000,
    env: 8,
    labels: { app: "inventory", tier: "backend" },
    updated: "2 hours ago",
  },
  {
    id: 2,
    name: "auth-service",
    image: "registry.local/auth-service:v1.8.0",
    namespace: "production",
    status: "Running",
    replicas: 3,
    readyReplicas: 3,
    cpu: "85m",
    memory: "128Mi",
    created: "5 hours ago",
    sortDate: 2,
    port: 3001,
    env: 6,
    labels: { app: "auth", tier: "backend" },
    updated: "3 hours ago",
  },
  {
    id: 3,
    name: "payment-api",
    image: "registry.local/payment-api:v3.0.2",
    namespace: "production",
    status: "Updating",
    replicas: 2,
    readyReplicas: 1,
    cpu: "150m",
    memory: "384Mi",
    created: "1 day ago",
    sortDate: 3,
    port: 3002,
    env: 10,
    labels: { app: "payment", tier: "backend" },
    updated: "30 min ago",
  },
  {
    id: 4,
    name: "notification-svc",
    image: "registry.local/notification-svc:v1.0.1",
    namespace: "staging",
    status: "Running",
    replicas: 1,
    readyReplicas: 1,
    cpu: "45m",
    memory: "96Mi",
    created: "3 days ago",
    sortDate: 4,
    port: 3003,
    env: 4,
    labels: { app: "notification", tier: "backend" },
    updated: "1 day ago",
  },
  {
    id: 5,
    name: "log-processor",
    image: "registry.local/log-processor:v0.5.0",
    namespace: "default",
    status: "Failed",
    replicas: 1,
    readyReplicas: 0,
    cpu: "0m",
    memory: "0Mi",
    created: "6 days ago",
    sortDate: 5,
    port: 3004,
    env: 3,
    labels: { app: "logging", tier: "infra" },
    updated: "2 days ago",
  },
  {
    id: 6,
    name: "frontend-web",
    image: "registry.local/frontend-web:v4.2.1",
    namespace: "production",
    status: "Running",
    replicas: 5,
    readyReplicas: 5,
    cpu: "200m",
    memory: "512Mi",
    created: "1 week ago",
    sortDate: 6,
    port: 80,
    env: 12,
    labels: { app: "frontend", tier: "frontend" },
    updated: "4 days ago",
  },
  {
    id: 7,
    name: "cache-redis",
    image: "registry.local/cache-redis:v6.2.0",
    namespace: "production",
    status: "Running",
    replicas: 2,
    readyReplicas: 2,
    cpu: "300m",
    memory: "1Gi",
    created: "1 week ago",
    sortDate: 7,
    port: 6379,
    env: 2,
    labels: { app: "cache", tier: "data" },
    updated: "1 week ago",
  },
  {
    id: 8,
    name: "db-postgres",
    image: "registry.local/db-postgres:v15.4",
    namespace: "production",
    status: "Running",
    replicas: 1,
    readyReplicas: 1,
    cpu: "500m",
    memory: "2Gi",
    created: "2 weeks ago",
    sortDate: 8,
    port: 5432,
    env: 5,
    labels: { app: "database", tier: "data" },
    updated: "1 week ago",
  },
  {
    id: 9,
    name: "message-queue",
    image: "registry.local/message-queue:v3.9.1",
    namespace: "production",
    status: "Running",
    replicas: 3,
    readyReplicas: 3,
    cpu: "180m",
    memory: "768Mi",
    created: "2 weeks ago",
    sortDate: 9,
    port: 9092,
    env: 4,
    labels: { app: "messaging", tier: "backend" },
    updated: "5 days ago",
  },
  {
    id: 10,
    name: "api-gateway",
    image: "registry.local/api-gateway:v2.1.0",
    namespace: "production",
    status: "Running",
    replicas: 2,
    readyReplicas: 2,
    cpu: "100m",
    memory: "256Mi",
    created: "2 weeks ago",
    sortDate: 10,
    port: 8080,
    env: 7,
    labels: { app: "gateway", tier: "infra" },
    updated: "6 days ago",
  },
  {
    id: 11,
    name: "ml-inference",
    image: "registry.local/ml-inference:v0.9.0",
    namespace: "development",
    status: "Pending",
    replicas: 1,
    readyReplicas: 0,
    cpu: "2",
    memory: "4Gi",
    created: "30 min ago",
    sortDate: 0.5,
    port: 5000,
    env: 6,
    labels: { app: "ml", tier: "compute" },
    updated: "30 min ago",
  },
  {
    id: 12,
    name: "search-indexer",
    image: "registry.local/search-indexer:v1.4.0",
    namespace: "staging",
    status: "Scaling",
    replicas: 3,
    readyReplicas: 1,
    cpu: "250m",
    memory: "512Mi",
    created: "4 hours ago",
    sortDate: 1.5,
    port: 9200,
    env: 5,
    labels: { app: "search", tier: "backend" },
    updated: "10 min ago",
  },
  {
    id: 13,
    name: "cdn-origin",
    image: "registry.local/cdn-origin:v2.0.0",
    namespace: "production",
    status: "Running",
    replicas: 3,
    readyReplicas: 3,
    cpu: "90m",
    memory: "192Mi",
    created: "3 weeks ago",
    sortDate: 11,
    port: 3005,
    env: 3,
    labels: { app: "cdn", tier: "infra" },
    updated: "2 weeks ago",
  },
  {
    id: 14,
    name: "scheduler-worker",
    image: "registry.local/scheduler-worker:v1.1.0",
    namespace: "default",
    status: "Running",
    replicas: 2,
    readyReplicas: 2,
    cpu: "75m",
    memory: "128Mi",
    created: "1 month ago",
    sortDate: 12,
    port: 3006,
    env: 4,
    labels: { app: "scheduler", tier: "backend" },
    updated: "1 week ago",
  },
  {
    id: 15,
    name: "audit-logger",
    image: "registry.local/audit-logger:v0.3.0",
    namespace: "development",
    status: "Updating",
    replicas: 1,
    readyReplicas: 0,
    cpu: "50m",
    memory: "64Mi",
    created: "2 hours ago",
    sortDate: 1.2,
    port: 3007,
    env: 3,
    labels: { app: "audit", tier: "infra" },
    updated: "15 min ago",
  },
];
